import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";


export const metadata = {
  title: "AI Career Coach",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <ClerkProvider 
      appearance={{
        baseTheme: dark,
      }}
    >
    <html lang="en"  suppressHydrationWarning>
      <body
        className=""
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {/* header */}
          <Header />
          <main className="min-h-screen">
            {children}
          </main>
          {/* footer */}
          <footer className="py-12">
            <div className="container mx-auto px-4 text-center text-gray-200">
              <p className="">
                Made with ❤️ by Abdul
              </p>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
